baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "Notes on open data and transparency"

contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = true 
canonifyurls = true
theme = "hugo-tufte"
hideReadTime = true

[taxonomies]
  category = "categories" 
  group = "groups"
  series = "series"
  tag = "tags"

[params]
  subtitle = "Beneficial ownership, corporate disclosure, tax justice, supply chains, policy and history"
  copyrightHolder = "Jack Lord"
  showPoweredBy = true

# -----------------------------------------------------------------------
# Navigation menu 
# -----------------------------------------------------------------------
[[menu.nav]]
  name = "Home"
  pre = "<i class='fa fa-home fa-lg'></i> "
  weight = -110 
  identifier = "home"
  url = "/"
[[menu.nav]]
  name = "About"
  pre = "<i class='fa fa-info-circle fa-lg'></i> "
   weight = -100 
  identifier = "about"
  url = "/about"
[[menu.nav]]
  name = "Posts"
  pre = "<i class='fa fa-book fa-lg'></i> "
  weight = -90 
  identifier = "posts"
  url = "/post"
[[menu.nav]]
  name = "Categories"
  pre = "<i class='fa fa-tags fa-lg'></i> "
  weight = -80 
  identifier = "categories"
  url = "/categories"


# -----------------------------------------------------------------------
# Footer menu 
# -----------------------------------------------------------------------
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-github fa-2x'></i> "
  weight = -100 
  identifier = "github"
  url = "https://github.com/ScatteredInk/open-data-notes"
[[menu.footer]]
  name = ""
  pre = "<i class='fa fa-twitter fa-2x'></i> "
  weight = -90 
  identifier = "twitter"
  url = "https://twitter.com/jacklord"

